// pnpm os:install-autostart — make the OS always-on. Registers two Windows Task
// Scheduler entries (no admin required, user-level):
//   • AI-OS-Autostart   — at logon → run the supervisor (brings the stack up)
//   • AI-OS-Supervisor  — every 3 min → self-heal (recovers after the laptop
//                         sleeps, which drops the pm2 daemon)
// Both invoke a generated wrapper .cmd that sets PATH (Task Scheduler runs with a
// minimal environment) and calls `pnpm os:watch`. Idempotent (/f replaces).
// Pass --uninstall to remove the tasks. Windows-only.
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { writeFileSync, rmSync } from 'node:fs';
import { C, run } from './ops.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const LOGON_TASK = 'AI-OS-Autostart';
const WATCH_TASK = 'AI-OS-Supervisor';
const WRAPPER = join(root, 'scripts', 'aios-autostart.cmd');
// A .vbs shim is the piece that makes this INVISIBLE. Pointing Task Scheduler
// (or Startup) straight at the .cmd makes Windows allocate a console — a cmd
// window popped up on every single run, which is intolerable every few minutes.
// WScript.Shell.Run(..., 0, False) launches the wrapper with a HIDDEN window.
const SHIM = join(root, 'scripts', 'aios-autostart.vbs');
const STARTUP_VBS = join(process.env.APPDATA ?? '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', 'AI-OS.vbs');
const STARTUP_CMD_LEGACY = join(process.env.APPDATA ?? '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', 'AI-OS.cmd');
// Every 3 minutes was needlessly chatty; 10 still recovers fast after a sleep.
const INTERVAL_MIN = Number(process.env.AIOS_SUPERVISOR_INTERVAL_MIN) || 10;

async function uninstall(): Promise<void> {
  for (const t of [LOGON_TASK, WATCH_TASK]) {
    const r = await run('schtasks', ['/delete', '/tn', t, '/f'], { timeoutMs: 20_000 });
    console.log(r.code === 0 ? C.green(`✓ removed ${t}`) : C.dim(`· ${t} not present`));
  }
  for (const f of [STARTUP_VBS, STARTUP_CMD_LEGACY, SHIM]) {
    try {
      rmSync(f, { force: true });
    } catch {
      /* not present */
    }
  }
  console.log(C.green('✓ removed logon launcher + shim'));
}

async function install(): Promise<void> {
  if (process.platform !== 'win32') {
    console.log(C.red('os:install-autostart is Windows-only (Task Scheduler).'));
    process.exit(1);
  }

  // Resolve the dirs Task Scheduler's minimal env won't have on PATH.
  const nodeDir = dirname(process.execPath); // C:\Program Files\nodejs
  const npmDir = join(process.env.APPDATA ?? '', 'npm'); // where pnpm.cmd lives
  const dockerBin = process.env.AIOS_DOCKER_BIN ?? 'C:\\Program Files\\Docker\\Docker\\resources\\bin';
  const ffmpegBin =
    process.env.AIOS_FFMPEG_DIR ??
    'C:\\Users\\jinuk\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-8.1.2-full_build\\bin';
  const ytdlpDir =
    process.env.AIOS_YTDLP_DIR ?? 'C:\\Users\\jinuk\\AppData\\Local\\Microsoft\\WinGet\\Packages\\yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe';

  const wrapper = [
    '@echo off',
    'REM AI OS self-heal wrapper — invoked by Windows Task Scheduler (logon + every',
    'REM 3 min). TS runs with a minimal environment, so set PATH explicitly, cd to',
    'REM the repo, and run the idempotent supervisor. Generated by os:install-autostart.',
    `set "PATH=${nodeDir};${npmDir};${dockerBin};${ffmpegBin};${ytdlpDir};%PATH%"`,
    `cd /d "${root}"`,
    'call pnpm os:watch >> "logs\\supervisor.log" 2>&1',
    '',
  ].join('\r\n');
  writeFileSync(WRAPPER, wrapper);
  console.log(C.green(`✓ wrote wrapper ${WRAPPER}`));

  // The invisible-launch shim. Both the scheduled task and the logon launcher
  // point at a .vbs (never the .cmd directly) so no console window is ever
  // created — the "0" is the hidden window style and False means don't wait.
  const vbs = [
    "' AI OS silent launcher — generated by os:install-autostart.",
    "' Runs the PATH-setting wrapper with a HIDDEN window (0) so the supervisor",
    "' never flashes a cmd/conhost window while you are working.",
    "' WAIT for the wrapper (True), so the task's exit code reflects the real work.",
    "' With False, wscript returned 0 instantly and Task Scheduler reported success",
    "' even when nothing ran — a false green, which is the bug class we keep killing.",
    `WScript.Quit CreateObject("WScript.Shell").Run("""${WRAPPER}""", 0, True)`,
    '',
  ].join('\r\n');
  writeFileSync(SHIM, vbs);
  console.log(C.green(`✓ wrote silent shim ${SHIM}`));

  // Boot-on-login is OPT-IN (--logon). It is genuinely intrusive on Windows:
  // bringing the stack up at login restarts dev servers and (if Docker is down)
  // wants a GUI, which is how this feature ended up interrupting the user.
  // Default now: periodic self-heal only, while you are already working.
  try {
    rmSync(STARTUP_CMD_LEGACY, { force: true }); // drop the old window-popping version
  } catch {
    /* not present */
  }
  if (process.argv.includes('--logon')) {
    try {
      writeFileSync(STARTUP_VBS, vbs);
      console.log(C.green(`✓ logon launcher ${STARTUP_VBS}`));
    } catch (e) {
      console.log(C.red(`✗ could not write logon launcher: ${e instanceof Error ? e.message : String(e)}`));
    }
  } else {
    try {
      rmSync(STARTUP_VBS, { force: true });
    } catch {
      /* not present */
    }
    console.log(C.dim('· no logon launcher (pass --logon to start the OS when you sign in)'));
  }

  // NO periodic Task Scheduler entry any more — measured, not assumed:
  // Task Scheduler fired the task, reported Last Result 0, and did NO work
  // (verified 3 times: no log line, no backup marker), while the identical
  // `wscript //B <shim>` command did the full job when run manually. A watchdog
  // that reports success while doing nothing is the precise failure mode this
  // supervisor exists to prevent, so it is gone.
  //
  // Periodic supervision now runs as the pm2 app `ai-os-supervisor` (--loop):
  // pm2 spawns it detached with no console, so it is genuinely silent, and pm2
  // restarts it if it dies. Honest gap: it cannot resurrect the pm2 daemon
  // itself — after a sleep/reboot that kills pm2, run `pnpm os:up` once.
  await run('schtasks', ['/delete', '/tn', WATCH_TASK, '/f'], { timeoutMs: 15_000 }); // clear any legacy entry
  console.log(C.green('✓ periodic self-heal runs under pm2 (ai-os-supervisor) — silent, and it actually executes'));

  // NB deliberately NOT recommending Docker Desktop's "start when you sign in":
  // it launches a GUI window in the user's face at every logon. The supervisor
  // waits for Docker instead of starting it (and never launches GUI apps).
  console.log(C.dim('\n  Docker must be running for the OS to recover. Start Docker Desktop when you want the OS up;'));
  console.log(C.dim('  the supervisor will not launch it (that would pop a window at you).'));
  console.log(C.dim('  Remove with: pnpm os:install-autostart --uninstall\n'));
}

if (process.argv.includes('--uninstall')) await uninstall();
else await install();
