// pnpm os:install-autostart — make the OS always-on. Registers two Windows Task
// Scheduler entries (no admin required, user-level):
//   • AI-OS-Autostart   — at logon → run the supervisor (brings the stack up)
//   • AI-OS-Supervisor  — every 3 min → self-heal (recovers after the laptop
//                         sleeps, which drops the pm2 daemon)
// Both invoke a generated wrapper .cmd that sets PATH (Task Scheduler runs with a
// minimal environment) and calls `pnpm os:watch`. Idempotent (/f replaces).
// Pass --uninstall to remove the tasks. Windows-only.
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { writeFileSync, rmSync } from 'node:fs';
import { C, run } from './ops.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const LOGON_TASK = 'AI-OS-Autostart';
const WATCH_TASK = 'AI-OS-Supervisor';
const WRAPPER = join(root, 'scripts', 'aios-autostart.cmd');
const STARTUP_CMD = join(process.env.APPDATA ?? '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', 'AI-OS.cmd');

async function uninstall(): Promise<void> {
  for (const t of [LOGON_TASK, WATCH_TASK]) {
    const r = await run('schtasks', ['/delete', '/tn', t, '/f'], { timeoutMs: 20_000 });
    console.log(r.code === 0 ? C.green(`✓ removed ${t}`) : C.dim(`· ${t} not present`));
  }
  try {
    rmSync(STARTUP_CMD, { force: true });
    console.log(C.green('✓ removed logon launcher'));
  } catch {
    /* not present */
  }
}

async function install(): Promise<void> {
  if (process.platform !== 'win32') {
    console.log(C.red('os:install-autostart is Windows-only (Task Scheduler).'));
    process.exit(1);
  }

  // Resolve the dirs Task Scheduler's minimal env won't have on PATH.
  const nodeDir = dirname(process.execPath); // C:\Program Files\nodejs
  const npmDir = join(process.env.APPDATA ?? '', 'npm'); // where pnpm.cmd lives
  const dockerBin = process.env.AIOS_DOCKER_BIN ?? 'C:\\Program Files\\Docker\\Docker\\resources\\bin';
  const ffmpegBin =
    process.env.AIOS_FFMPEG_DIR ??
    'C:\\Users\\jinuk\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-8.1.2-full_build\\bin';
  const ytdlpDir =
    process.env.AIOS_YTDLP_DIR ?? 'C:\\Users\\jinuk\\AppData\\Local\\Microsoft\\WinGet\\Packages\\yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe';

  const wrapper = [
    '@echo off',
    'REM AI OS self-heal wrapper — invoked by Windows Task Scheduler (logon + every',
    'REM 3 min). TS runs with a minimal environment, so set PATH explicitly, cd to',
    'REM the repo, and run the idempotent supervisor. Generated by os:install-autostart.',
    `set "PATH=${nodeDir};${npmDir};${dockerBin};${ffmpegBin};${ytdlpDir};%PATH%"`,
    `cd /d "${root}"`,
    'call pnpm os:watch >> "logs\\supervisor.log" 2>&1',
    '',
  ].join('\r\n');
  writeFileSync(WRAPPER, wrapper);
  console.log(C.green(`✓ wrote wrapper ${WRAPPER}`));

  // Boot-on-login (admin-free): a launcher in the user's Startup folder runs the
  // wrapper minimized at logon. (schtasks /sc onlogon needs admin on this box.)
  try {
    writeFileSync(STARTUP_CMD, `@echo off\r\nstart "" /min "${WRAPPER}"\r\n`);
    console.log(C.green(`✓ logon launcher ${STARTUP_CMD}`));
  } catch (e) {
    console.log(C.red(`✗ could not write logon launcher: ${e instanceof Error ? e.message : String(e)}`));
  }

  // Every 3 minutes, all day, every day: self-heal (recovers after sleep).
  const watch = await run(
    'schtasks',
    ['/create', '/tn', WATCH_TASK, '/tr', WRAPPER, '/sc', 'daily', '/st', '00:00', '/ri', '3', '/du', '24:00', '/rl', 'limited', '/f'],
    { timeoutMs: 20_000 },
  );
  console.log(watch.code === 0 ? C.green(`✓ registered ${WATCH_TASK} (every 3 min)`) : C.red(`✗ ${WATCH_TASK} failed: ${watch.out.trim().slice(-200)}`));

  console.log(C.dim('\n  Also enable Docker Desktop → Settings → "Start Docker Desktop when you sign in" for the fastest cold boot.'));
  console.log(C.dim('  Remove with: pnpm os:install-autostart --uninstall\n'));
}

if (process.argv.includes('--uninstall')) await uninstall();
else await install();
